//todo http://ddragon.leagueoflegends.com/cdn/8.24.1/data/zh_CN/champion.json
export const championId2Name = {
    '1': {id: 'Annie', name: '黑暗之女'},
    '2': {id: 'Olaf', name: '狂战士'},
    '3': {id: 'Galio', name: '正义巨像'},
    '4': {id: 'TwistedFate', name: '卡牌大师'},
    '5': {id: 'XinZhao', name: '德邦总管'},
    '6': {id: 'Urgot', name: '无畏战车'},
    '7': {id: 'Leblanc', name: '诡术妖姬'},
    '8': {id: 'Vladimir', name: '猩红收割者'},
    '9': {id: 'Fiddlesticks', name: '末日使者'},
    '10': {id: 'Kayle', name: '审判天使'},
    '11': {id: 'MasterYi', name: '无极剑圣'},
    '12': {id: 'Alistar', name: '牛头酋长'},
    '13': {id: 'Ryze', name: '符文法师'},
    '14': {id: 'Sion', name: '亡灵战神'},
    '15': {id: 'Sivir', name: '战争女神'},
    '16': {id: 'Soraka', name: '众星之子'},
    '17': {id: 'Teemo', name: '迅捷斥候'},
    '18': {id: 'Tristana', name: '麦林炮手'},
    '19': {id: 'Warwick', name: '祖安怒兽'},
    '20': {id: 'Nunu', name: '雪原双子'},
    '21': {id: 'MissFortune', name: '赏金猎人'},
    '22': {id: 'Ashe', name: '寒冰射手'},
    '23': {id: 'Tryndamere', name: '蛮族之王'},
    '24': {id: 'Jax', name: '武器大师'},
    '25': {id: 'Morgana', name: '堕落天使'},
    '26': {id: 'Zilean', name: '时光守护者'},
    '27': {id: 'Singed', name: '炼金术士'},
    '28': {id: 'Evelynn', name: '痛苦之拥'},
    '29': {id: 'Twitch', name: '瘟疫之源'},
    '30': {id: 'Karthus', name: '死亡颂唱者'},
    '31': {id: 'Chogath', name: '虚空恐惧'},
    '32': {id: 'Amumu', name: '殇之木乃伊'},
    '33': {id: 'Rammus', name: '披甲龙龟'},
    '34': {id: 'Anivia', name: '冰晶凤凰'},
    '35': {id: 'Shaco', name: '恶魔小丑'},
    '36': {id: 'DrMundo', name: '祖安狂人'},
    '37': {id: 'Sona', name: '琴瑟仙女'},
    '38': {id: 'Kassadin', name: '虚空行者'},
    '39': {id: 'Irelia', name: '刀锋舞者'},
    '40': {id: 'Janna', name: '风暴之怒'},
    '41': {id: 'Gangplank', name: '海洋之灾'},
    '42': {id: 'Corki', name: '英勇投弹手'},
    '43': {id: 'Karma', name: '天启者'},
    '44': {id: 'Taric', name: '瓦洛兰之盾'},
    '45': {id: 'Veigar', name: '邪恶小法师'},
    '48': {id: 'Trundle', name: '巨魔之王'},
    '50': {id: 'Swain', name: '诺克萨斯统领'},
    '51': {id: 'Caitlyn', name: '皮城女警'},
    '53': {id: 'Blitzcrank', name: '蒸汽机器人'},
    '54': {id: 'Malphite', name: '熔岩巨兽'},
    '55': {id: 'Katarina', name: '不祥之刃'},
    '56': {id: 'Nocturne', name: '永恒梦魇'},
    '57': {id: 'Maokai', name: '扭曲树精'},
    '58': {id: 'Renekton', name: '荒漠屠夫'},
    '59': {id: 'JarvanIV', name: '德玛西亚皇子'},
    '60': {id: 'Elise', name: '蜘蛛女皇'},
    '61': {id: 'Orianna', name: '发条魔灵'},
    '62': {id: 'MonkeyKing', name: '齐天大圣'},
    '63': {id: 'Brand', name: '复仇焰魂'},
    '64': {id: 'LeeSin', name: '盲僧'},
    '67': {id: 'Vayne', name: '暗夜猎手'},
    '68': {id: 'Rumble', name: '机械公敌'},
    '69': {id: 'Cassiopeia', name: '魔蛇之拥'},
    '72': {id: 'Skarner', name: '水晶先锋'},
    '74': {id: 'Heimerdinger', name: '大发明家'},
    '75': {id: 'Nasus', name: '沙漠死神'},
    '76': {id: 'Nidalee', name: '狂野女猎手'},
    '77': {id: 'Udyr', name: '兽灵行者'},
    '78': {id: 'Poppy', name: '圣锤之毅'},
    '79': {id: 'Gragas', name: '酒桶'},
    '80': {id: 'Pantheon', name: '战争之王'},
    '81': {id: 'Ezreal', name: '探险家'},
    '82': {id: 'Mordekaiser', name: '铁铠冥魂'},
    '83': {id: 'Yorick', name: '牧魂人'},
    '84': {id: 'Akali', name: '离群之刺'},
    '85': {id: 'Kennen', name: '狂暴之心'},
    '86': {id: 'Garen', name: '德玛西亚之力'},
    '89': {id: 'Leona', name: '曙光女神'},
    '90': {id: 'Malzahar', name: '虚空先知'},
    '91': {id: 'Talon', name: '刀锋之影'},
    '92': {id: 'Riven', name: '放逐之刃'},
    '96': {id: 'KogMaw', name: '深渊巨口'},
    '98': {id: 'Shen', name: '暮光之眼'},
    '99': {id: 'Lux', name: '光辉女郎'},
    '101': {id: 'Xerath', name: '远古巫灵'},
    '102': {id: 'Shyvana', name: '龙血武姬'},
    '103': {id: 'Ahri', name: '九尾妖狐'},
    '104': {id: 'Graves', name: '法外狂徒'},
    '105': {id: 'Fizz', name: '潮汐海灵'},
    '106': {id: 'Volibear', name: '雷霆咆哮'},
    '107': {id: 'Rengar', name: '傲之追猎者'},
    '110': {id: 'Varus', name: '惩戒之箭'},
    '111': {id: 'Nautilus', name: '深海泰坦'},
    '112': {id: 'Viktor', name: '机械先驱'},
    '113': {id: 'Sejuani', name: '北地之怒'},
    '114': {id: 'Fiora', name: '无双剑姬'},
    '115': {id: 'Ziggs', name: '爆破鬼才'},
    '117': {id: 'Lulu', name: '仙灵女巫'},
    '119': {id: 'Draven', name: '荣耀行刑官'},
    '120': {id: 'Hecarim', name: '战争之影'},
    '121': {id: 'Khazix', name: '虚空掠夺者'},
    '122': {id: 'Darius', name: '诺克萨斯之手'},
    '126': {id: 'Jayce', name: '未来守护者'},
    '127': {id: 'Lissandra', name: '冰霜女巫'},
    '131': {id: 'Diana', name: '皎月女神'},
    '133': {id: 'Quinn', name: '德玛西亚之翼'},
    '134': {id: 'Syndra', name: '暗黑元首'},
    '136': {id: 'AurelionSol', name: '铸星龙王'},
    '141': {id: 'Kayn', name: '影流之镰'},
    '142': {id: 'Zoe', name: '暮光星灵'},
    '143': {id: 'Zyra', name: '荆棘之兴'},
    '145': {id: 'Kaisa', name: '虚空之女'},
    '150': {id: 'Gnar', name: '迷失之牙'},
    '154': {id: 'Zac', name: '生化魔人'},
    '157': {id: 'Yasuo', name: '疾风剑豪'},
    '161': {id: 'Velkoz', name: '虚空之眼'},
    '163': {id: 'Taliyah', name: '岩雀'},
    '164': {id: 'Camille', name: '青钢影'},
    '201': {id: 'Braum', name: '弗雷尔卓德之心'},
    '202': {id: 'Jhin', name: '戏命师'},
    '203': {id: 'Kindred', name: '永猎双子'},
    '222': {id: 'Jinx', name: '暴走萝莉'},
    '223': {id: 'TahmKench', name: '河流之王'},
    '236': {id: 'Lucian', name: '圣枪游侠'},
    '238': {id: 'Zed', name: '影流之主'},
    '240': {id: 'Kled', name: '暴怒骑士'},
    '245': {id: 'Ekko', name: '时间刺客'},
    '254': {id: 'Vi', name: '皮城执法官'},
    '266': {id: 'Aatrox', name: '暗裔剑魔'},
    '267': {id: 'Nami', name: '唤潮鲛姬'},
    '268': {id: 'Azir', name: '沙漠皇帝'},
    '412': {id: 'Thresh', name: '魂锁典狱长'},
    '420': {id: 'Illaoi', name: '海兽祭司'},
    '421': {id: 'RekSai', name: '虚空遁地兽'},
    '427': {id: 'Ivern', name: '翠神'},
    '429': {id: 'Kalista', name: '复仇之矛'},
    '432': {id: 'Bard', name: '星界游神'},
    '497': {id: 'Rakan', name: '幻翎'},
    '498': {id: 'Xayah', name: '逆羽'},
    '516': {id: 'Ornn', name: '山隐之焰'},
    '518': {id: 'Neeko', name: '万花通灵'},
    '555': {id: 'Pyke', name: '血港鬼影'}
};

export const spellId2Name = {
    '1': 'SummonerBoost',
    '3': 'SummonerExhaust',
    '4': 'SummonerFlash',
    '6': 'SummonerHaste',
    '7': 'SummonerHeal',
    '11': 'SummonerSmite',
    '12': 'SummonerTeleport',
    '13': 'SummonerMana',
    '14': 'SummonerDot',
    '21': 'SummonerBarrier',
    '30': 'SummonerPoroRecall',
    '31': 'SummonerPoroThrow',
    '32': 'SummonerSnowball',
    '33': 'SummonerSiegeChampSelect1',
    '34': 'SummonerSiegeChampSelect2',
    '35': 'SummonerDarkStarChampSelect1',
    '36': 'SummonerDarkStarChampSelect2',
    '39': 'SummonerSnowURFSnowball_Mark',
    '50': 'SummonerOdysseyRevive',
    '51': 'SummonerOdysseyGhost',
    '52': 'SummonerOdysseyFlash'
};

//http://ddragon.leagueoflegends.com/cdn/8.24.1/data/zh_CN/runesReforged.json
export const runeId2Name =
    {
        '8000': 'Precision',
        '8100': 'Domination',
        '8200': 'Sorcery',
        '8300': 'Inspiration',
        '8400': 'Resolve'
    };

export const match_queues = {
    420: "单人排位",
    430: "匹配模式",
    440: "灵活组排",
    450: "极地大乱斗"
};

// module.exports = {
//     championId2Name
// };