export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SUMMONER_DETAIL = "SET_SUMMONER_DETAIL";
export const SUMMONER_LOADING = "SUMMONER_LOADING";
export const SET_SUMMONER_INPUT_ERR = "SET_SUMMONER_INPUT_ERR";
