

const accountId = "bcDNFeTGUe6rrlUSY4zJtTUcU0xoEnMfyN44ulINQg-J";

const game = {
    "seasonId": 11,
    "queueId": 420,
    "gameId": 3477995519,
    "participantIdentities": [
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "밤이싫어",
                "matchHistoryUri": "/v1/stats/player_history/KR/200242402",
                "platformId": "KR",
                "currentAccountId": "FtNoVd0sefAw9k4ptv7Hq4yGx1Vv43JmNe6ohGCPLR3PRyA",
                "profileIcon": 3791,
                "summonerId": "1IRYb5Dj3UdpdAKhOTKKGaaaZzMVPNuP8nt3CkDsA1CY4kQ",
                "accountId": "FtNoVd0sefAw9k4ptv7Hq4yGx1Vv43JmNe6ohGCPLR3PRyA"
            },
            "participantId": 1
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "욕한번안해본사람",
                "matchHistoryUri": "/v1/stats/player_history/KR/200427073",
                "platformId": "KR",
                "currentAccountId": "3Ti5u_gXtvUTLK7XYDdnBwCOIXUkRF2q6L65d69sUOQuwQE",
                "profileIcon": 7,
                "summonerId": "QLd1gRBkzd7I1sto8-R8gQkysQKJ-x-N0h6aFS9_gnH5fjs",
                "accountId": "3Ti5u_gXtvUTLK7XYDdnBwCOIXUkRF2q6L65d69sUOQuwQE"
            },
            "participantId": 2
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "SKT T1 Haru",
                "matchHistoryUri": "/v1/stats/player_history/KR/207477934",
                "platformId": "KR",
                "currentAccountId": "rXZQj45k4E1X2h0ajvvtXOi68REYMfZs0fLrCGs5MGKoRC8",
                "profileIcon": 3849,
                "summonerId": "I50wdYPl0OwaiNeqWRwNS6v-OzWdnd2SvYzahEaDAS2twBM",
                "accountId": "rXZQj45k4E1X2h0ajvvtXOi68REYMfZs0fLrCGs5MGKoRC8"
            },
            "participantId": 3
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "1wandy",
                "matchHistoryUri": "/v1/stats/player_history/KR/201666307",
                "platformId": "KR",
                "currentAccountId": "I1FkC6fLhneAo7GPEMtjfSXNyY1ryAILerwQhG0bdttXerY",
                "profileIcon": 3545,
                "summonerId": "ZPw-x4DFvtuyc9i2gUjhXrbc6iFybPcQwjfM68q79y96Jiw",
                "accountId": "I1FkC6fLhneAo7GPEMtjfSXNyY1ryAILerwQhG0bdttXerY"
            },
            "participantId": 4
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "up jug up",
                "matchHistoryUri": "/v1/stats/player_history/KR/5749255",
                "platformId": "KR",
                "currentAccountId": "CtPtZR6mD0dVy_cVzzb2A3zMfxaY0AQMEBsnB6HbkXO6",
                "profileIcon": 23,
                "summonerId": "4rjG8ETn9QKsjx0C3GoUvLt72qGPhRsR1jtD4NRCUd7gSg",
                "accountId": "CtPtZR6mD0dVy_cVzzb2A3zMfxaY0AQMEBsnB6HbkXO6"
            },
            "participantId": 5
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "Hide on bush",
                "matchHistoryUri": "/v1/stats/player_history/KR/3440481",
                "platformId": "KR",
                "currentAccountId": "bcDNFeTGUe6rrlUSY4zJtTUcU0xoEnMfyN44ulINQg-J",
                "profileIcon": 6,
                "summonerId": "DpRRmZrrpxRdUkHcqoJIncrj9R70PFh1j_w225GfURO9rA",
                "accountId": "bcDNFeTGUe6rrlUSY4zJtTUcU0xoEnMfyN44ulINQg-J"
            },
            "participantId": 6
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "Last Dream Yuki",
                "matchHistoryUri": "/v1/stats/player_history/KR/208887268",
                "platformId": "KR",
                "currentAccountId": "UFj_ahAynu3KMbEbschXl4Zc2YWLYSv5emcrPdb70K0TV70",
                "profileIcon": 3790,
                "summonerId": "H8jIvzaUnKWPMpA-YvZs2fQo1QIwgvBehtWFd7RK0iZJGG4",
                "accountId": "UFj_ahAynu3KMbEbschXl4Zc2YWLYSv5emcrPdb70K0TV70"
            },
            "participantId": 7
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "xubinfanss",
                "matchHistoryUri": "/v1/stats/player_history/KR/206490625",
                "platformId": "KR",
                "currentAccountId": "VaKZ94rexFZRtvCKW49DCXUMW1rXpzM3isz8gxdQEhOmB2I",
                "profileIcon": 1644,
                "summonerId": "QgXH_oA-6g1pOqM8SVUVWAR8uU-jnxczPZL3gfN8gCd9RRI",
                "accountId": "VaKZ94rexFZRtvCKW49DCXUMW1rXpzM3isz8gxdQEhOmB2I"
            },
            "participantId": 8
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "qegadadgqef",
                "matchHistoryUri": "/v1/stats/player_history/KR/732311",
                "platformId": "KR",
                "currentAccountId": "4duOV1FqDMHtFUeCe3ClVYLlMHUY11Q3eggzskuRnRo",
                "profileIcon": 772,
                "summonerId": "ysQBZ6T9J3LgCG1FOOid7La5DQs4xzvkhXWVZ7WrUYm5iA",
                "accountId": "4duOV1FqDMHtFUeCe3ClVYLlMHUY11Q3eggzskuRnRo"
            },
            "participantId": 9
        },
        {
            "player": {
                "currentPlatformId": "KR",
                "summonerName": "SKT T1 Crazy",
                "matchHistoryUri": "/v1/stats/player_history/KR/6241698",
                "platformId": "KR",
                "currentAccountId": "hfquWZOwTbkZnVTLCld8LIfWxG86-SDdJcpqboq4_pFu",
                "profileIcon": 6,
                "summonerId": "W17lmRukcJT2FBeo5lEKdfQTA_MlWhqRjCUumXM9r2emXw",
                "accountId": "hfquWZOwTbkZnVTLCld8LIfWxG86-SDdJcpqboq4_pFu"
            },
            "participantId": 10
        }
    ],
    "gameVersion": "8.24.255.8524",
    "platformId": "KR",
    "gameMode": "CLASSIC",
    "mapId": 11,
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "firstDragon": false,
            "bans": [
                {
                    "pickTurn": 1,
                    "championId": 81
                },
                {
                    "pickTurn": 2,
                    "championId": -1
                },
                {
                    "pickTurn": 3,
                    "championId": 91
                },
                {
                    "pickTurn": 4,
                    "championId": 84
                },
                {
                    "pickTurn": 5,
                    "championId": 145
                }
            ],
            "firstInhibitor": false,
            "win": "Fail",
            "firstRiftHerald": true,
            "firstBaron": false,
            "baronKills": 0,
            "riftHeraldKills": 1,
            "firstBlood": true,
            "teamId": 100,
            "firstTower": true,
            "vilemawKills": 0,
            "inhibitorKills": 0,
            "towerKills": 2,
            "dominionVictoryScore": 0,
            "dragonKills": 0
        },
        {
            "firstDragon": true,
            "bans": [
                {
                    "pickTurn": 6,
                    "championId": -1
                },
                {
                    "pickTurn": 7,
                    "championId": 555
                },
                {
                    "pickTurn": 8,
                    "championId": 236
                },
                {
                    "pickTurn": 9,
                    "championId": 518
                },
                {
                    "pickTurn": 10,
                    "championId": 121
                }
            ],
            "firstInhibitor": false,
            "win": "Win",
            "firstRiftHerald": false,
            "firstBaron": true,
            "baronKills": 1,
            "riftHeraldKills": 0,
            "firstBlood": false,
            "teamId": 200,
            "firstTower": false,
            "vilemawKills": 0,
            "inhibitorKills": 0,
            "towerKills": 2,
            "dominionVictoryScore": 0,
            "dragonKills": 3
        }
    ],
    "participants": [
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 4,
                "visionScore": 17,
                "magicDamageDealtToChampions": 2500,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 307,
                "longestTimeSpentLiving": 665,
                "perk1Var1": 96,
                "perk1Var3": 0,
                "perk1Var2": 100,
                "tripleKills": 0,
                "perk5": 8233,
                "perk4": 8226,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 2,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 19,
                "perk5Var3": 0,
                "perk5Var2": 10,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 4,
                "statPerk1": 5008,
                "statPerk0": 5005,
                "damageDealtToTurrets": 1002,
                "physicalDamageDealtToChampions": 6714,
                "damageDealtToObjectives": 1002,
                "perk2Var2": 30,
                "perk2Var3": 0,
                "totalUnitsHealed": 4,
                "perk2Var1": 19,
                "perk4Var1": 250,
                "totalDamageTaken": 10901,
                "perk4Var3": 0,
                "wardsKilled": 2,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "quadraKills": 0,
                "magicDamageDealt": 12006,
                "firstBloodAssist": false,
                "item2": 3153,
                "item3": 1054,
                "item0": 3111,
                "item1": 3091,
                "item6": 3363,
                "item4": 1042,
                "item5": 2055,
                "perk1": 9111,
                "perk0": 8008,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 163,
                "damageSelfMitigated": 7128,
                "magicalDamageTaken": 6550,
                "perk0Var2": 0,
                "trueDamageTaken": 549,
                "assists": 3,
                "perk4Var2": 291,
                "goldSpent": 8050,
                "trueDamageDealt": 7778,
                "participantId": 1,
                "physicalDamageDealt": 76424,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 9355,
                "physicalDamageTaken": 3801,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 96209,
                "neutralMinionsKilledEnemyJungle": 0,
                "deaths": 6,
                "wardsPlaced": 11,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 140,
                "goldEarned": 8807,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 13,
                "doubleKills": 1,
                "inhibitorKills": 0,
                "perk0Var1": 1,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 4,
                "pentaKills": 0,
                "totalHeal": 974,
                "totalMinionsKilled": 187,
                "timeCCingOthers": 16,
                "statPerk2": 5003
            },
            "spell1Id": 7,
            "participantId": 1,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "BOTTOM",
                "participantId": 1,
                "csDiffPerMinDeltas": {
                    "0-10": -0.44999999999999996,
                    "10-20": -0.5499999999999994
                },
                "goldPerMinDeltas": {
                    "0-10": 249,
                    "10-20": 409.1
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -16.899999999999977,
                    "10-20": -27.849999999999994
                },
                "creepsPerMinDeltas": {
                    "0-10": 6.3,
                    "10-20": 8.3
                },
                "xpPerMinDeltas": {
                    "0-10": 316.5,
                    "10-20": 477.5
                },
                "role": "DUO_CARRY",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 140.35000000000002,
                    "10-20": -105.49999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 319.29999999999995,
                    "10-20": 250.5
                }
            },
            "championId": 110
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 5,
                "visionScore": 15,
                "magicDamageDealtToChampions": 0,
                "largestMultiKill": 0,
                "totalTimeCrowdControlDealt": 156,
                "longestTimeSpentLiving": 1424,
                "perk1Var1": 1579,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8135,
                "perk4": 8139,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 0,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 876,
                "perk5Var3": 0,
                "perk5Var2": 1,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 13,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 2687,
                "physicalDamageDealtToChampions": 8891,
                "damageDealtToObjectives": 4027,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 721,
                "perk4Var1": 818,
                "totalDamageTaken": 20556,
                "perk4Var3": 0,
                "wardsKilled": 2,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 0,
                "firstBloodAssist": false,
                "item2": 3071,
                "item3": 1055,
                "item0": 3142,
                "item1": 2055,
                "item6": 3340,
                "item4": 3111,
                "item5": 1054,
                "perk1": 8446,
                "perk0": 8439,
                "perk3": 8453,
                "perk2": 8473,
                "perk3Var3": 0,
                "perk3Var2": 63,
                "perk3Var1": 988,
                "damageSelfMitigated": 12537,
                "magicalDamageTaken": 4711,
                "perk0Var2": 0,
                "trueDamageTaken": 377,
                "assists": 4,
                "perk4Var2": 0,
                "goldSpent": 8475,
                "trueDamageDealt": 6080,
                "participantId": 2,
                "physicalDamageDealt": 122435,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 8891,
                "physicalDamageTaken": 15467,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 128515,
                "neutralMinionsKilledEnemyJungle": 6,
                "deaths": 1,
                "wardsPlaced": 9,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8100,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 9222,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": true,
                "firstTowerKill": false,
                "champLevel": 14,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 0,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 5,
                "pentaKills": 0,
                "totalHeal": 8234,
                "totalMinionsKilled": 203,
                "timeCCingOthers": 11,
                "statPerk2": 5002
            },
            "spell1Id": 12,
            "participantId": 2,
            "highestAchievedSeasonTier": "DIAMOND",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "TOP",
                "participantId": 2,
                "csDiffPerMinDeltas": {
                    "0-10": 1.7999999999999998,
                    "10-20": -0.20000000000000018
                },
                "goldPerMinDeltas": {
                    "0-10": 296.9,
                    "10-20": 403.4
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 133.3,
                    "10-20": 19.899999999999977
                },
                "creepsPerMinDeltas": {
                    "0-10": 7.7,
                    "10-20": 9.1
                },
                "xpPerMinDeltas": {
                    "0-10": 479.5,
                    "10-20": 544.5
                },
                "role": "SOLO",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 103.19999999999996,
                    "10-20": 15.80000000000004
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 616,
                    "10-20": 625.3
                }
            },
            "championId": 266
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 8,
                "visionScore": 20,
                "magicDamageDealtToChampions": 6897,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 72,
                "longestTimeSpentLiving": 416,
                "perk1Var1": 479,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 9105,
                "perk4": 8009,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 4,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 16,
                "perk5Var3": 0,
                "perk5Var2": 10,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 12,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 766,
                "physicalDamageDealtToChampions": 359,
                "damageDealtToObjectives": 766,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 0,
                "perk2Var1": 371,
                "perk4Var1": 721,
                "totalDamageTaken": 14037,
                "perk4Var3": 0,
                "wardsKilled": 2,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 3,
                "quadraKills": 0,
                "magicDamageDealt": 90201,
                "firstBloodAssist": false,
                "item2": 1026,
                "item3": 1082,
                "item0": 3152,
                "item1": 2033,
                "item6": 3340,
                "item4": 3165,
                "item5": 3020,
                "perk1": 8446,
                "perk0": 8439,
                "perk3": 8242,
                "perk2": 8473,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 6,
                "damageSelfMitigated": 11005,
                "magicalDamageTaken": 5665,
                "perk0Var2": 0,
                "trueDamageTaken": 1565,
                "assists": 1,
                "perk4Var2": 52,
                "goldSpent": 8450,
                "trueDamageDealt": 8495,
                "participantId": 3,
                "physicalDamageDealt": 4692,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 7776,
                "physicalDamageTaken": 6805,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 103388,
                "neutralMinionsKilledEnemyJungle": 0,
                "deaths": 5,
                "wardsPlaced": 10,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8000,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 520,
                "goldEarned": 8978,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 13,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 121,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 2,
                "pentaKills": 0,
                "totalHeal": 0,
                "totalMinionsKilled": 174,
                "timeCCingOthers": 18,
                "statPerk2": 5001
            },
            "spell1Id": 14,
            "participantId": 3,
            "highestAchievedSeasonTier": "MASTER",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 3,
                "csDiffPerMinDeltas": {
                    "0-10": -1.7000000000000002,
                    "10-20": -1.7000000000000006
                },
                "goldPerMinDeltas": {
                    "0-10": 268.4,
                    "10-20": 442.9
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -82.6,
                    "10-20": 39.400000000000034
                },
                "creepsPerMinDeltas": {
                    "0-10": 6.8,
                    "10-20": 8.9
                },
                "xpPerMinDeltas": {
                    "0-10": 409.5,
                    "10-20": 561.9000000000001
                },
                "role": "SOLO",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -134.09999999999997,
                    "10-20": -193.7
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 350.7,
                    "10-20": 425.1
                }
            },
            "championId": 3
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 0,
                "visionScore": 57,
                "magicDamageDealtToChampions": 8088,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 246,
                "longestTimeSpentLiving": 377,
                "perk1Var1": 250,
                "perk1Var3": 0,
                "perk1Var2": 425,
                "tripleKills": 0,
                "perk5": 8345,
                "perk4": 8347,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 1,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 4,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 456,
                "physicalDamageDealtToChampions": 1147,
                "damageDealtToObjectives": 456,
                "perk2Var2": 50,
                "perk2Var3": 0,
                "totalUnitsHealed": 4,
                "perk2Var1": 19,
                "perk4Var1": 0,
                "totalDamageTaken": 13447,
                "perk4Var3": 0,
                "wardsKilled": 11,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 24843,
                "firstBloodAssist": false,
                "item2": 2055,
                "item3": 3174,
                "item0": 3092,
                "item1": 2031,
                "item6": 3364,
                "item4": 1082,
                "item5": 3158,
                "perk1": 8226,
                "perk0": 8229,
                "perk3": 8237,
                "perk2": 8233,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 367,
                "damageSelfMitigated": 6012,
                "magicalDamageTaken": 7550,
                "perk0Var2": 0,
                "trueDamageTaken": 1212,
                "assists": 6,
                "perk4Var2": 0,
                "goldSpent": 6225,
                "trueDamageDealt": 799,
                "participantId": 4,
                "physicalDamageDealt": 3337,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 10034,
                "physicalDamageTaken": 4685,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 28980,
                "neutralMinionsKilledEnemyJungle": 0,
                "deaths": 8,
                "wardsPlaced": 35,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8300,
                "turretKills": 0,
                "firstBloodKill": true,
                "trueDamageDealtToChampions": 799,
                "goldEarned": 6588,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 10,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 989,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 11,
                "pentaKills": 0,
                "totalHeal": 1437,
                "totalMinionsKilled": 27,
                "timeCCingOthers": 21,
                "statPerk2": 5001
            },
            "spell1Id": 14,
            "participantId": 4,
            "highestAchievedSeasonTier": "UNRANKED",
            "spell2Id": 4,
            "teamId": 100,
            "timeline": {
                "lane": "BOTTOM",
                "participantId": 4,
                "csDiffPerMinDeltas": {
                    "0-10": -0.44999999999999996,
                    "10-20": -0.5499999999999994
                },
                "goldPerMinDeltas": {
                    "0-10": 238,
                    "10-20": 261.6
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -16.899999999999977,
                    "10-20": -27.849999999999994
                },
                "creepsPerMinDeltas": {
                    "0-10": 1.1,
                    "10-20": 1.4
                },
                "xpPerMinDeltas": {
                    "0-10": 275.5,
                    "10-20": 285.9
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 140.35000000000002,
                    "10-20": -105.49999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 431.7,
                    "10-20": 389.8
                }
            },
            "championId": 43
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 65,
                "visionScore": 41,
                "magicDamageDealtToChampions": 13007,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 205,
                "longestTimeSpentLiving": 421,
                "perk1Var1": 233,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8236,
                "perk4": 8233,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 8,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 24,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 97,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 686,
                "physicalDamageDealtToChampions": 712,
                "damageDealtToObjectives": 18895,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 4,
                "perk2Var1": 30,
                "perk4Var1": 19,
                "totalDamageTaken": 18030,
                "perk4Var3": 0,
                "wardsKilled": 11,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "quadraKills": 0,
                "magicDamageDealt": 111648,
                "firstBloodAssist": false,
                "item2": 3070,
                "item3": 3070,
                "item0": 3070,
                "item1": 3070,
                "item6": 3364,
                "item4": 3070,
                "item5": 3070,
                "perk1": 8143,
                "perk0": 8128,
                "perk3": 8105,
                "perk2": 8138,
                "perk3Var3": 0,
                "perk3Var2": 4,
                "perk3Var1": 11,
                "damageSelfMitigated": 8705,
                "magicalDamageTaken": 3920,
                "perk0Var2": 14,
                "trueDamageTaken": 1194,
                "assists": 2,
                "perk4Var2": 0,
                "goldSpent": 15150,
                "trueDamageDealt": 8504,
                "participantId": 5,
                "physicalDamageDealt": 14022,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 14196,
                "physicalDamageTaken": 12915,
                "totalPlayerScore": 0,
                "win": false,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 134175,
                "neutralMinionsKilledEnemyJungle": 10,
                "deaths": 5,
                "wardsPlaced": 11,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8200,
                "turretKills": 2,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 476,
                "goldEarned": 10691,
                "killingSprees": 3,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": true,
                "champLevel": 13,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 924,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 7,
                "pentaKills": 0,
                "totalHeal": 9956,
                "totalMinionsKilled": 26,
                "timeCCingOthers": 0,
                "statPerk2": 5001
            },
            "spell1Id": 4,
            "participantId": 5,
            "highestAchievedSeasonTier": "DIAMOND",
            "spell2Id": 11,
            "teamId": 100,
            "timeline": {
                "lane": "JUNGLE",
                "participantId": 5,
                "csDiffPerMinDeltas": {
                    "0-10": 0,
                    "10-20": 0.09999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 356.2,
                    "10-20": 490.70000000000005
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 18.900000000000006,
                    "10-20": 89.29999999999998
                },
                "creepsPerMinDeltas": {
                    "0-10": 0,
                    "10-20": 1.5
                },
                "xpPerMinDeltas": {
                    "0-10": 337.4,
                    "10-20": 581
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 142.20000000000002,
                    "10-20": 60.900000000000006
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 629.1,
                    "10-20": 713.1
                }
            },
            "championId": 76
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 0,
                "visionScore": 27,
                "magicDamageDealtToChampions": 2792,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 71,
                "longestTimeSpentLiving": 533,
                "perk1Var1": 1165,
                "perk1Var3": 0,
                "perk1Var2": 280,
                "tripleKills": 0,
                "perk5": 8120,
                "perk4": 8143,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 8,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 7,
                "perk5Var3": 0,
                "perk5Var2": 35,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 4,
                "statPerk1": 5008,
                "statPerk0": 5005,
                "damageDealtToTurrets": 3802,
                "physicalDamageDealtToChampions": 8860,
                "damageDealtToObjectives": 14110,
                "perk2Var2": 30,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 8,
                "perk4Var1": 354,
                "totalDamageTaken": 16702,
                "perk4Var3": 0,
                "wardsKilled": 6,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 5,
                "quadraKills": 0,
                "magicDamageDealt": 14128,
                "firstBloodAssist": false,
                "item2": 1057,
                "item3": 3078,
                "item0": 3748,
                "item1": 2421,
                "item6": 3340,
                "item4": 3111,
                "item5": 1038,
                "perk1": 9111,
                "perk0": 8010,
                "perk3": 8014,
                "perk2": 9104,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 345,
                "damageSelfMitigated": 11345,
                "magicalDamageTaken": 7938,
                "perk0Var2": 0,
                "trueDamageTaken": 780,
                "assists": 6,
                "perk4Var2": 0,
                "goldSpent": 11978,
                "trueDamageDealt": 12683,
                "participantId": 6,
                "physicalDamageDealt": 134670,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 13999,
                "physicalDamageTaken": 7983,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 161482,
                "neutralMinionsKilledEnemyJungle": 0,
                "deaths": 3,
                "wardsPlaced": 11,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "turretKills": 1,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 2345,
                "goldEarned": 12616,
                "killingSprees": 2,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 15,
                "doubleKills": 1,
                "inhibitorKills": 0,
                "perk0Var1": 654,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 4,
                "pentaKills": 0,
                "totalHeal": 5484,
                "totalMinionsKilled": 229,
                "timeCCingOthers": 13,
                "statPerk2": 5003
            },
            "spell1Id": 14,
            "participantId": 6,
            "highestAchievedSeasonTier": "MASTER",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "MIDDLE",
                "participantId": 6,
                "csDiffPerMinDeltas": {
                    "0-10": 1.7000000000000002,
                    "10-20": 1.7000000000000006
                },
                "goldPerMinDeltas": {
                    "0-10": 417,
                    "10-20": 422.4
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 82.6,
                    "10-20": -39.400000000000034
                },
                "creepsPerMinDeltas": {
                    "0-10": 8.5,
                    "10-20": 10.600000000000001
                },
                "xpPerMinDeltas": {
                    "0-10": 492.1,
                    "10-20": 522.5
                },
                "role": "SOLO",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": 134.09999999999997,
                    "10-20": 193.7
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 484.79999999999995,
                    "10-20": 618.8
                }
            },
            "championId": 39
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 0,
                "visionScore": 59,
                "magicDamageDealtToChampions": 3269,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 48,
                "longestTimeSpentLiving": 740,
                "perk1Var1": 250,
                "perk1Var3": 0,
                "perk1Var2": 237,
                "tripleKills": 0,
                "perk5": 8345,
                "perk4": 8313,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 1,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 4,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 0,
                "statPerk1": 5002,
                "statPerk0": 5007,
                "damageDealtToTurrets": 493,
                "physicalDamageDealtToChampions": 716,
                "damageDealtToObjectives": 1374,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 0,
                "perk4Var1": 0,
                "totalDamageTaken": 10751,
                "perk4Var3": 0,
                "wardsKilled": 12,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 0,
                "quadraKills": 0,
                "magicDamageDealt": 5445,
                "firstBloodAssist": false,
                "item2": 3092,
                "item3": 1028,
                "item0": 2055,
                "item1": 3157,
                "item6": 3364,
                "item4": 0,
                "item5": 3117,
                "perk1": 8226,
                "perk0": 8214,
                "perk3": 8232,
                "perk2": 8210,
                "perk3Var3": 0,
                "perk3Var2": 10,
                "perk3Var1": 4,
                "damageSelfMitigated": 6061,
                "magicalDamageTaken": 6624,
                "perk0Var2": 60,
                "trueDamageTaken": 216,
                "assists": 11,
                "perk4Var2": 0,
                "goldSpent": 6900,
                "trueDamageDealt": 743,
                "participantId": 7,
                "physicalDamageDealt": 3066,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 4681,
                "physicalDamageTaken": 3911,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 9255,
                "neutralMinionsKilledEnemyJungle": 0,
                "deaths": 3,
                "wardsPlaced": 29,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8300,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 695,
                "goldEarned": 6907,
                "killingSprees": 0,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 11,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 585,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 12,
                "pentaKills": 0,
                "totalHeal": 1825,
                "totalMinionsKilled": 16,
                "timeCCingOthers": 26,
                "statPerk2": 5003
            },
            "spell1Id": 14,
            "participantId": 7,
            "highestAchievedSeasonTier": "DIAMOND",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "BOTTOM",
                "participantId": 7,
                "csDiffPerMinDeltas": {
                    "0-10": 0.44999999999999996,
                    "10-20": 0.5499999999999994
                },
                "goldPerMinDeltas": {
                    "0-10": 187.5,
                    "10-20": 269.6
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 16.899999999999977,
                    "10-20": 27.849999999999994
                },
                "creepsPerMinDeltas": {
                    "0-10": 0.3,
                    "10-20": 1.1
                },
                "xpPerMinDeltas": {
                    "0-10": 281.7,
                    "10-20": 248.39999999999998
                },
                "role": "DUO_SUPPORT",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -140.35000000000002,
                    "10-20": 105.49999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 258.5,
                    "10-20": 369.70000000000005
                }
            },
            "championId": 25
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 16,
                "visionScore": 23,
                "magicDamageDealtToChampions": 11256,
                "largestMultiKill": 2,
                "totalTimeCrowdControlDealt": 5061,
                "longestTimeSpentLiving": 663,
                "perk1Var1": 250,
                "perk1Var3": 0,
                "perk1Var2": 1002,
                "tripleKills": 0,
                "perk5": 8345,
                "perk4": 8352,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 7,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 4,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 24,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 428,
                "physicalDamageDealtToChampions": 618,
                "damageDealtToObjectives": 15582,
                "perk2Var2": 40,
                "perk2Var3": 0,
                "totalUnitsHealed": 3,
                "perk2Var1": 19,
                "perk4Var1": 269,
                "totalDamageTaken": 11599,
                "perk4Var3": 851,
                "wardsKilled": 4,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 6,
                "quadraKills": 0,
                "magicDamageDealt": 127581,
                "firstBloodAssist": false,
                "item2": 2033,
                "item3": 1026,
                "item0": 3102,
                "item1": 3285,
                "item6": 3363,
                "item4": 0,
                "item5": 3116,
                "perk1": 8226,
                "perk0": 8229,
                "perk3": 8237,
                "perk2": 8233,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 248,
                "damageSelfMitigated": 4373,
                "magicalDamageTaken": 4468,
                "perk0Var2": 0,
                "trueDamageTaken": 64,
                "assists": 2,
                "perk4Var2": 1337,
                "goldSpent": 10925,
                "trueDamageDealt": 2720,
                "participantId": 8,
                "physicalDamageDealt": 5672,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 11875,
                "physicalDamageTaken": 7066,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 135975,
                "neutralMinionsKilledEnemyJungle": 4,
                "deaths": 2,
                "wardsPlaced": 10,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8300,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 0,
                "goldEarned": 11002,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 15,
                "doubleKills": 2,
                "inhibitorKills": 0,
                "perk0Var1": 1175,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 4,
                "pentaKills": 0,
                "totalHeal": 6281,
                "totalMinionsKilled": 209,
                "timeCCingOthers": 15,
                "statPerk2": 5001
            },
            "spell1Id": 4,
            "participantId": 8,
            "highestAchievedSeasonTier": "DIAMOND",
            "spell2Id": 7,
            "teamId": 200,
            "timeline": {
                "lane": "BOTTOM",
                "participantId": 8,
                "csDiffPerMinDeltas": {
                    "0-10": 0.44999999999999996,
                    "10-20": 0.5499999999999994
                },
                "goldPerMinDeltas": {
                    "0-10": 388,
                    "10-20": 385.9
                },
                "xpDiffPerMinDeltas": {
                    "0-10": 16.899999999999977,
                    "10-20": 27.849999999999994
                },
                "creepsPerMinDeltas": {
                    "0-10": 8,
                    "10-20": 9.7
                },
                "xpPerMinDeltas": {
                    "0-10": 344.1,
                    "10-20": 570.7
                },
                "role": "DUO_CARRY",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -140.35000000000002,
                    "10-20": 105.49999999999997
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 211.8,
                    "10-20": 481.6
                }
            },
            "championId": 69
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 68,
                "visionScore": 44,
                "magicDamageDealtToChampions": 9980,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 395,
                "longestTimeSpentLiving": 417,
                "perk1Var1": 394,
                "perk1Var3": 0,
                "perk1Var2": 0,
                "tripleKills": 0,
                "perk5": 8347,
                "perk4": 8304,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 6,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 0,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 108,
                "statPerk1": 5008,
                "statPerk0": 5005,
                "damageDealtToTurrets": 797,
                "physicalDamageDealtToChampions": 1237,
                "damageDealtToObjectives": 15005,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 30,
                "perk4Var1": 8,
                "totalDamageTaken": 17007,
                "perk4Var3": 0,
                "wardsKilled": 11,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 4,
                "quadraKills": 0,
                "magicDamageDealt": 70103,
                "firstBloodAssist": false,
                "item2": 3165,
                "item3": 1082,
                "item0": 2420,
                "item1": 3191,
                "item6": 3364,
                "item4": 1402,
                "item5": 3020,
                "perk1": 8126,
                "perk0": 8112,
                "perk3": 8105,
                "perk2": 8138,
                "perk3Var3": 0,
                "perk3Var2": 5,
                "perk3Var1": 14,
                "damageSelfMitigated": 6411,
                "magicalDamageTaken": 8700,
                "perk0Var2": 0,
                "trueDamageTaken": 230,
                "assists": 10,
                "perk4Var2": 0,
                "goldSpent": 9150,
                "trueDamageDealt": 8450,
                "participantId": 9,
                "physicalDamageDealt": 23013,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 12514,
                "physicalDamageTaken": 8076,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 101567,
                "neutralMinionsKilledEnemyJungle": 10,
                "deaths": 2,
                "wardsPlaced": 10,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8300,
                "turretKills": 0,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 1296,
                "goldEarned": 10114,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 14,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 929,
                "combatPlayerScore": 0,
                "perk0Var3": 0,
                "visionWardsBoughtInGame": 7,
                "pentaKills": 0,
                "totalHeal": 8828,
                "totalMinionsKilled": 19,
                "timeCCingOthers": 22,
                "statPerk2": 5001
            },
            "spell1Id": 4,
            "participantId": 9,
            "highestAchievedSeasonTier": "DIAMOND",
            "spell2Id": 11,
            "teamId": 200,
            "timeline": {
                "lane": "JUNGLE",
                "participantId": 9,
                "csDiffPerMinDeltas": {
                    "0-10": 0,
                    "10-20": -0.09999999999999998
                },
                "goldPerMinDeltas": {
                    "0-10": 318.1,
                    "10-20": 380.29999999999995
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -18.900000000000006,
                    "10-20": -89.29999999999998
                },
                "creepsPerMinDeltas": {
                    "0-10": 0,
                    "10-20": 1.4
                },
                "xpPerMinDeltas": {
                    "0-10": 318.5,
                    "10-20": 491.70000000000005
                },
                "role": "NONE",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -142.20000000000002,
                    "10-20": -60.900000000000006
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 486.9,
                    "10-20": 652.2
                }
            },
            "championId": 60
        },
        {
            "stats": {
                "neutralMinionsKilledTeamJungle": 7,
                "visionScore": 23,
                "magicDamageDealtToChampions": 479,
                "largestMultiKill": 1,
                "totalTimeCrowdControlDealt": 112,
                "longestTimeSpentLiving": 501,
                "perk1Var1": 357,
                "perk1Var3": 0,
                "perk1Var2": 80,
                "tripleKills": 0,
                "perk5": 8446,
                "perk4": 8473,
                "playerScore9": 0,
                "playerScore8": 0,
                "kills": 3,
                "playerScore1": 0,
                "playerScore0": 0,
                "playerScore3": 0,
                "playerScore2": 0,
                "playerScore5": 0,
                "playerScore4": 0,
                "playerScore7": 0,
                "playerScore6": 0,
                "perk5Var1": 849,
                "perk5Var3": 0,
                "perk5Var2": 0,
                "totalScoreRank": 0,
                "neutralMinionsKilled": 14,
                "statPerk1": 5008,
                "statPerk0": 5008,
                "damageDealtToTurrets": 1221,
                "physicalDamageDealtToChampions": 11969,
                "damageDealtToObjectives": 4086,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "totalUnitsHealed": 1,
                "perk2Var1": 23,
                "perk4Var1": 453,
                "totalDamageTaken": 19121,
                "perk4Var3": 0,
                "wardsKilled": 5,
                "largestCriticalStrike": 0,
                "largestKillingSpree": 2,
                "quadraKills": 0,
                "magicDamageDealt": 1378,
                "firstBloodAssist": false,
                "item2": 3748,
                "item3": 3071,
                "item0": 1055,
                "item1": 2031,
                "item6": 3340,
                "item4": 1028,
                "item5": 3111,
                "perk1": 9111,
                "perk0": 8005,
                "perk3": 8299,
                "perk2": 9105,
                "perk3Var3": 0,
                "perk3Var2": 0,
                "perk3Var1": 503,
                "damageSelfMitigated": 12104,
                "magicalDamageTaken": 5424,
                "perk0Var2": 832,
                "trueDamageTaken": 645,
                "assists": 1,
                "perk4Var2": 0,
                "goldSpent": 8800,
                "trueDamageDealt": 8347,
                "participantId": 10,
                "physicalDamageDealt": 114134,
                "sightWardsBoughtInGame": 0,
                "totalDamageDealtToChampions": 13010,
                "physicalDamageTaken": 13052,
                "totalPlayerScore": 0,
                "win": true,
                "objectivePlayerScore": 0,
                "totalDamageDealt": 123860,
                "neutralMinionsKilledEnemyJungle": 0,
                "deaths": 5,
                "wardsPlaced": 10,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8400,
                "turretKills": 1,
                "firstBloodKill": false,
                "trueDamageDealtToChampions": 562,
                "goldEarned": 9280,
                "killingSprees": 1,
                "unrealKills": 0,
                "firstTowerAssist": false,
                "firstTowerKill": false,
                "champLevel": 14,
                "doubleKills": 0,
                "inhibitorKills": 0,
                "perk0Var1": 1194,
                "combatPlayerScore": 0,
                "perk0Var3": 362,
                "visionWardsBoughtInGame": 2,
                "pentaKills": 0,
                "totalHeal": 4154,
                "totalMinionsKilled": 183,
                "timeCCingOthers": 21,
                "statPerk2": 5002
            },
            "spell1Id": 14,
            "participantId": 10,
            "highestAchievedSeasonTier": "MASTER",
            "spell2Id": 4,
            "teamId": 200,
            "timeline": {
                "lane": "TOP",
                "participantId": 10,
                "csDiffPerMinDeltas": {
                    "0-10": -1.7999999999999998,
                    "10-20": 0.20000000000000018
                },
                "goldPerMinDeltas": {
                    "0-10": 212.8,
                    "10-20": 381.7
                },
                "xpDiffPerMinDeltas": {
                    "0-10": -133.3,
                    "10-20": -19.899999999999977
                },
                "creepsPerMinDeltas": {
                    "0-10": 5.9,
                    "10-20": 9.3
                },
                "xpPerMinDeltas": {
                    "0-10": 346.20000000000005,
                    "10-20": 524.6
                },
                "role": "SOLO",
                "damageTakenDiffPerMinDeltas": {
                    "0-10": -103.19999999999996,
                    "10-20": -15.80000000000004
                },
                "damageTakenPerMinDeltas": {
                    "0-10": 512.8,
                    "10-20": 609.5
                }
            },
            "championId": 58
        }
    ],
    "gameDuration": 1521,
    "gameCreation": 1546225987073
};


//根据账户id从比赛人员基本信息中查找被查询的参与者
const findRequestParticipantIdentityByAccountId = (participantIdentities, accountId) => {
    return participantIdentities.find((participantIdentity) => {
        return accountId === participantIdentity["player"]["accountId"]
    })
};

//根据参与者id从比赛人员详细信息中查找被查询的参与者
const findRequestParticipantByParticipantId = (participants, participantId) => {
    return participants.find((participant) => {
        return participantId === participant["participantId"]
    })
};

const {participantIdentities, participants} = game;

console.log(findRequestParticipantIdentityByAccountId(participantIdentities, accountId));

const {participantId} = findRequestParticipantIdentityByAccountId(participantIdentities, accountId);

console.log(participantId);

console.log(findRequestParticipantByParticipantId(participants, participantId));

const {championId, spell1Id, spell2Id, teamId, stats} =
    findRequestParticipantByParticipantId(participants, participantId);

console.log("championId = %s,spell1Id = %s, spell2Id = %s, teamId = %s", championId, spell1Id, spell2Id, teamId);

const {perkPrimaryStyle, perkSubStyle} = stats;
console.log("perkPrimaryStyle = %s,perkSubStyle = %s", perkPrimaryStyle, perkSubStyle);

const championName = championId2Name[266];

console.log(championName);